### ISSUE TITLE
Strange HintPaths in csprojs

### ISSUE THREAD

**Issue by knatten** [zivid/csharp-extra-samples#5]
For some reason we have these `HintPath`s in all our csprojs:
```csproj
    <Reference Include="ZividCoreNET">
      <HintPath>..\..\..\..\..\..\Program Files\Zivid\bin\ZividCoreNET.dll</HintPath>
    </Reference>
    <Reference Include="ZividVis3DNET">
      <HintPath>..\..\..\..\..\..\Program Files\Zivid\bin\ZividVis3DNET.dll</HintPath>
    </Reference>
```

I don't understand why they're there, I assume this will only work if you happen to have cloned this repo at a very specific folder depth.

Maybe we should use `ZIVID_INSTALL_FOLDER` here, like we do in the `xcopy` commands? And maybe we should then specify the full path to the dll in the `Include=` attribute, instead of using a `HintPath` element?

I'm not sure what the best practice is here, but what we're currently doing seems wrong.

**Comment by SatjaSivcev** [comment]
This happens when you add reference:
![image](https://user-images.githubusercontent.com/46567886/74658620-f96d8200-5192-11ea-851f-99be9c320abe.png)

**Comment by knatten** [comment]
Yes, and that might be convenient if you have a local project you're working on on your machine alone. But the paths will only be valid on that particular machine, and shouldn't be committed to a shared repository imo.

**Comment by SatjaSivcev** [comment]
Then instead we should have a tutorial on how to add references?

**Comment by knatten** [comment]
No we need to add these references, but we need to not give wrong `HintPath`s. I have two suggestions for that in the original issue description. I think @chrisasc is working on this now.

**Comment by SatjaSivcev** [comment]
I think this is fixed now, e.g. https://github.com/zivid/csharp-extra-samples/blob/master/source/Camera/Basic/Capture/Capture.csproj

**Comment by knatten** [comment]
Yup, we're all good:
```
👻 git grep HintPath | awk '{print $2}' |sort|uniq
<HintPath>$(ZIVID_INSTALL_FOLDER)\bin_debug\ZividCoreNET.dll</HintPath>
<HintPath>$(ZIVID_INSTALL_FOLDER)\bin_debug\ZividVis3DNET.dll</HintPath>
<HintPath>$(ZIVID_INSTALL_FOLDER)\bin\ZividCoreNET.dll</HintPath>
<HintPath>$(ZIVID_INSTALL_FOLDER)\bin\ZividVis3DNET.dll</HintPath>

```
