### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by knatten** [zivid/csharp-extra-samples#8]
When I click on the link to GetCameraIntrinsics in the readme, I get to this 404:

https://github.com/zivid/csharp-extra-samples/tree/source/master/Camera/InfoUtilOther/GetCameraIntrinsics/GetCameraIntrinsics.cs

**Comment by SatjaSivcev** [comment]
Made a PR #9

**Comment by SatjaSivcev** [comment]
Fixed with #9
